//! The primitives every view is made of; a widget never knows `AppState`.

mod badge;
mod button;
pub mod code;
mod counts;
mod field;
mod fold;
mod heading;
mod icon;
mod input;
mod list;
mod menu;
mod modal;
mod pane;
mod question;
mod scrolled;
mod search;
mod table;
mod tabs;
mod terminal;
mod toggle;

pub use badge::Badge;
pub use button::{Button, Text, picker, slot_at};
pub use counts::{changes, counts, counts_room};
pub use field::Field;
pub use fold::{caret, fold, folder};
pub use heading::Heading;
pub use icon::{busy, icon, lead, turned};
pub use input::input;
pub use list::{Row, list};
pub use menu::{menu, size as menu_size};
pub use modal::{Corner, modal, panel_at};
pub use pane::{Side, pane};
pub use question::{offer, question};
pub use scrolled::scrolled;
pub use search::Search;
pub use table::{Cell, Column, Rows, Shown, Sorted, Table, Width};
pub use tabs::{Tab, tabs};
pub use terminal::grid_of;
pub use terminal::screen;
pub use toggle::Toggle;
