// The frontend's single IPC type surface.
//
// Everything ts-rs can generate is re-exported from ./generated (the mechanical
// truth, regenerated by `pnpm gen:types` from the Rust structs). Hand-written
// types remain ONLY where the frontend deliberately narrows a field (unions the
// backend can't express) or where no Rust struct exists (forge JSON, event
// payloads, UI constants). Features import from THIS file, never ./generated.

import type {
  DiffLine as GDiffLine,
  Hunk as GHunk,
  FileDiff as GFileDiff,
  RepoDiff as GRepoDiff,
  DiffResult as GDiffResult,
  Annotation as GAnnotation,
  UiConfig as GUiConfig,
  TaskView,
  Worktree,
  Repo,
  SessionKind,
  NotionView,
  GitConfig,
} from './generated';

// ── Generated re-exports (identical shapes; aliased where the Rust name differs) ──

export type {
  TaskView as Task,
  Repo,
  Worktree,
  Mr,
  BlameLine,
  CommitEntry,
  WorktreeStatus,
  PropertyNames,
  StatusMap,
  FilterConfig,
  PropertySchema,
  StatusGroup,
  TaskSchema,
  RelationOption,
  PropertyValue,
  TimeSummary as TaskTime,
  HomeMr,
  HomeRepo,
  HomeEntry,
  ReviewMr,
  GitConfig,
  AgentState,
  ToolCall as AgentToolCall,
  AgentActivity,
  Environment,
  ToolCheck,
  DetectedSchema,
  NotionUser,
  FileLines,
  SessionKind,
} from './generated';

// ── Deliberate narrowings (rebuilt over the generated shapes) ─────────────────

/** `type` is a closed set on the wire (review/types.rs documents it); the union
 *  keeps the CM diff builder exhaustive. */
export type DiffLine = Omit<GDiffLine, 'type'> & { type: 'add' | 'del' | 'ctx' };

export type Hunk = Omit<GHunk, 'lines'> & { lines: DiffLine[] };

export type FileDiff = Omit<GFileDiff, 'hunks'> & {
  /** Empty in the summary payload — fetched lazily per file via get_file_diff. */
  hunks: Hunk[];
};

export type RepoDiff = Omit<GRepoDiff, 'files'> & { files: FileDiff[] };

export type DiffResult = Omit<GDiffResult, 'repos'> & { repos: RepoDiff[] };

/** `status` only ever holds these two values (store/annotations.rs). */
export type Annotation = Omit<GAnnotation, 'status'> & { status: 'open' | 'resolved' };

export type NotionConfig = NotionView;

export type ThemeName = 'frappe' | 'latte' | 'onedark' | 'onelight';

export const THEMES: { id: ThemeName; label: string }[] = [
  { id: 'latte',    label: 'Catppuccin Latte' },
  { id: 'frappe',   label: 'Catppuccin Frappé' },
  { id: 'onelight', label: 'One Light' },
  { id: 'onedark',  label: 'One Dark' },
];

export const DEFAULT_THEME: ThemeName = 'latte';
/** Base UI font size in px. Mirrors `default_font_size()` in core/config —
 *  the whole type ramp is derived from it (lib/theme.ts::applyFontSize). */
export const DEFAULT_FONT_SIZE = 15;

/** `theme` narrowed to the themes the CSS actually ships. */
export type UiConfig = Omit<GUiConfig, 'theme'> & { theme: ThemeName };

export interface Config {
  notion: NotionConfig;
  git: GitConfig;
  ui: UiConfig;
}

// ── No Rust struct behind these (forge JSON, pool scan, confirmation events) ──

/** One note within an MR discussion thread (GitLab/GitHub-normalized, loose). */
export interface ThreadNote {
  id?: number;
  created_at?: string;
  author?: { username?: string; name?: string };
  body?: string;
  resolved?: boolean;
  resolvable?: boolean;
  position?: {
    new_path?: string;
    new_line?: number;
    line_range?: { end?: { new_line?: number } };
  };
}

/** An MR discussion thread as returned by `get_mr_threads`. */
export interface MrThread {
  id?: string;
  notes?: ThreadNote[];
}

/** Rich MR/PR fields from `get_mr_details` — normalized across GitLab/GitHub. */
export interface MrDetails {
  title: string;
  description: string;
  author: string;
  source_branch: string;
  target_branch: string;
  state: string;
  draft: boolean;
  created_at: string;
  web_url: string;
  /** Approval state, folded in from the approvals endpoint. */
  approved?: boolean;
  /** True when the CURRENT user is among the approvers (GitLab only). */
  approved_by_me?: boolean;
  approved_by?: string[];
}

export interface SearchMatch {
  file: string;
  line: number;
  content: string;
}

/** The shape the `confirmation_requested` event carries (payload already parsed;
 *  deliberately NOT the generated PendingConfirmation, which is the raw DB row). */
export interface ConfirmationDto {
  id: string;
  session_id: string | null;
  op_type: string;
  payload: unknown;
  origin: 'ui' | 'mcp';
}

/** A clone under `<worktree_root>/main` — the repo pool the pickers list. */
export interface MainRepo {
  local_path: string;
  /** Path relative to the pool, e.g. "gitlab.example.com/devops/mayo" — the identity. */
  slug: string;
}

// ── Event payload types (Tauri events emitted from Rust) ─────────────────────

export interface WorkspaceStubEvent {
  task: TaskView;
  kind?: SessionKind;
}

export interface WorkspaceReadyEvent {
  task: TaskView;
  worktrees: Worktree[];
  repos: Repo[];
  kind?: SessionKind;
}

export interface ConfirmationRequestedEvent {
  id: string;
  session_id: string | null;
  op_type: string;
  payload: unknown;
  origin: 'ui' | 'mcp';
}

export interface ConfirmationResolvedEvent {
  id: string;
  session_id: string | null;
  approved: boolean;
  op_type: string;
  result: unknown;
  /** Non-null = the op was approved but FAILED (the confirmation row is gone; no
   *  retry). Null on a successful/denied resolution. */
  error: string | null;
}

export interface RebaseConflictEvent {
  worktree_id: string;
  files: string[];
}

export interface RebaseDoneEvent {
  worktree_id: string;
  aborted?: true;
}

export interface WorktreeClosedEvent {
  worktree_id: string;
  session_id: string;
  repo_id: string;
}

export interface PtyOutputEvent {
  session_id: string;
  /** The chunk, base64. A JSON array of numbers cost four characters per byte and
   *  a parse per byte on the UI thread — see the reader in core/pty. */
  b64: string;
}

export interface PtyExitEvent {
  session_id: string;
}

export interface PtyStartedEvent {
  session_id: string;
  task_id: string;
  /** "auth" = the forge-CLI sign-in shell (task_id "__auth__", no session). */
  pty_type: 'agent' | 'terminal' | 'auth';
}

export interface TaskPausedEvent {
  short_id: string;
}

export interface TaskFinishedEvent {
  short_id: string;
  done_status: string;
}
