[package]
name = "groove-ui"
description = "Draws AppState as a Frame and turns input into commands"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
groove-controllers = { path = "../../controllers/controllers" }
groove-gfx = { path = "../../base/gfx" }
groove-types = { path = "../../shared/types" }

[lints]
workspace = true
