//! The palettes a theme picks from.

use crate::Color;

/// Catppuccin, the names it uses.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Palette {
    pub crust: Color,
    pub mantle: Color,
    pub base: Color,
    pub surface0: Color,
    pub surface1: Color,
    pub surface2: Color,
    pub overlay0: Color,
    pub overlay1: Color,
    pub overlay2: Color,
    pub subtext0: Color,
    pub subtext1: Color,
    pub text: Color,
    pub rosewater: Color,
    pub flamingo: Color,
    pub pink: Color,
    pub mauve: Color,
    pub red: Color,
    pub maroon: Color,
    pub peach: Color,
    pub yellow: Color,
    pub green: Color,
    pub teal: Color,
    pub sky: Color,
    pub sapphire: Color,
    pub blue: Color,
    pub lavender: Color,
}

impl Palette {
    pub const MOCHA: Palette = Palette {
        crust: Color::hex(0x11111b),
        mantle: Color::hex(0x181825),
        base: Color::hex(0x1e1e2e),
        surface0: Color::hex(0x313244),
        surface1: Color::hex(0x45475a),
        surface2: Color::hex(0x585b70),
        overlay0: Color::hex(0x6c7086),
        overlay1: Color::hex(0x7f849c),
        overlay2: Color::hex(0x9399b2),
        subtext0: Color::hex(0xa6adc8),
        subtext1: Color::hex(0xbac2de),
        text: Color::hex(0xcdd6f4),
        rosewater: Color::hex(0xf5e0dc),
        flamingo: Color::hex(0xf2cdcd),
        pink: Color::hex(0xf5c2e7),
        mauve: Color::hex(0xcba6f7),
        red: Color::hex(0xf38ba8),
        maroon: Color::hex(0xeba0ac),
        peach: Color::hex(0xfab387),
        yellow: Color::hex(0xf9e2af),
        green: Color::hex(0xa6e3a1),
        teal: Color::hex(0x94e2d5),
        sky: Color::hex(0x89dceb),
        sapphire: Color::hex(0x74c7ec),
        blue: Color::hex(0x89b4fa),
        lavender: Color::hex(0xb4befe),
    };

    pub const FRAPPE: Palette = Palette {
        crust: Color::hex(0x232634),
        mantle: Color::hex(0x292c3c),
        base: Color::hex(0x303446),
        surface0: Color::hex(0x414559),
        surface1: Color::hex(0x51576d),
        surface2: Color::hex(0x626880),
        overlay0: Color::hex(0x737994),
        overlay1: Color::hex(0x838ba7),
        overlay2: Color::hex(0x949cbb),
        subtext0: Color::hex(0xa5adce),
        subtext1: Color::hex(0xb5bfe2),
        text: Color::hex(0xc6d0f5),
        rosewater: Color::hex(0xf2d5cf),
        flamingo: Color::hex(0xeebebe),
        pink: Color::hex(0xf4b8e4),
        mauve: Color::hex(0xca9ee6),
        red: Color::hex(0xe78284),
        maroon: Color::hex(0xea999c),
        peach: Color::hex(0xef9f76),
        yellow: Color::hex(0xe5c890),
        green: Color::hex(0xa6d189),
        teal: Color::hex(0x81c8be),
        sky: Color::hex(0x99d1db),
        sapphire: Color::hex(0x85c1dc),
        blue: Color::hex(0x8caaee),
        lavender: Color::hex(0xbabbf1),
    };

    pub const MACCHIATO: Palette = Palette {
        crust: Color::hex(0x181926),
        mantle: Color::hex(0x1e2030),
        base: Color::hex(0x24273a),
        surface0: Color::hex(0x363a4f),
        surface1: Color::hex(0x494d64),
        surface2: Color::hex(0x5b6078),
        overlay0: Color::hex(0x6e738d),
        overlay1: Color::hex(0x8087a2),
        overlay2: Color::hex(0x939ab7),
        subtext0: Color::hex(0xa5adcb),
        subtext1: Color::hex(0xb8c0e0),
        text: Color::hex(0xcad3f5),
        rosewater: Color::hex(0xf4dbd6),
        flamingo: Color::hex(0xf0c6c6),
        pink: Color::hex(0xf5bde6),
        mauve: Color::hex(0xc6a0f6),
        red: Color::hex(0xed8796),
        maroon: Color::hex(0xee99a0),
        peach: Color::hex(0xf5a97f),
        yellow: Color::hex(0xeed49f),
        green: Color::hex(0xa6da95),
        teal: Color::hex(0x8bd5ca),
        sky: Color::hex(0x91d7e3),
        sapphire: Color::hex(0x7dc4e4),
        blue: Color::hex(0x8aadf4),
        lavender: Color::hex(0xb7bdf8),
    };

    pub const LATTE: Palette = Palette {
        crust: Color::hex(0xdce0e8),
        mantle: Color::hex(0xe6e9ef),
        base: Color::hex(0xeff1f5),
        surface0: Color::hex(0xccd0da),
        surface1: Color::hex(0xbcc0cc),
        surface2: Color::hex(0xacb0be),
        overlay0: Color::hex(0x9ca0b0),
        overlay1: Color::hex(0x8c8fa1),
        overlay2: Color::hex(0x7c7f93),
        subtext0: Color::hex(0x6c6f85),
        subtext1: Color::hex(0x5c5f77),
        text: Color::hex(0x4c4f69),
        rosewater: Color::hex(0xdc8a78),
        flamingo: Color::hex(0xdd7878),
        pink: Color::hex(0xea76cb),
        mauve: Color::hex(0x8839ef),
        red: Color::hex(0xd20f39),
        maroon: Color::hex(0xe64553),
        peach: Color::hex(0xfe640b),
        yellow: Color::hex(0xdf8e1d),
        green: Color::hex(0x40a02b),
        teal: Color::hex(0x179299),
        sky: Color::hex(0x04a5e5),
        sapphire: Color::hex(0x209fb5),
        blue: Color::hex(0x1e66f5),
        lavender: Color::hex(0x7287fd),
    };
}
